# Generated by Django 3.0.1 on 2020-08-14 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200813_2001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='immm',
            new_name='info',
        ),
    ]
